name: surf_flutter_study_jam_2023
description: Michurin student
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  surf_lint_rules: ^2.1.0
  dio: ^5.1.1
  flutter_bloc: ^8.1.2
  shared_preferences: ^2.1.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
